### ISSUE TITLE
Crashing on login

### ISSUE THREAD

**Issue by Docxx** [jaminvanderberg/jCraft-Modpack#1]
Searching for AE2 meteors and I was getting a crash every couple of mins, now I can't login at all without crashing. Seems to be some mob spawning causing the crash. Here is my crash log.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 22/09/15 14:57
Description: Ticking screen

java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!
    at net.minecraft.entity.ai.attributes.RangedAttribute.<init>(SourceFile:14)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:1630)
    at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:71)
    at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:15)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by jaminvanderberg** [comment]
Check the update on the website (http://jcraftmc.com/update).  Apply it and let me know if that resolves your issue.

**Comment by Docxx** [comment]
fixed :)
